version: '3.8'
services:
  server:
    build: ./server
    container_name: squidgame-server
    ports:
      - "4000:4000"

  client:
    build: ./client
    container_name: squidgame-client
    ports:
      - "3001:3001"
    depends_on:
      - server

