version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
    ports:
      - "3001:80"
    depends_on:
      - server

