# ok test123
version: '3.8'
services:
  server:
    image: squid-game-server
    build:
      context: ./server
    ports:
      - "4000:4000"

  client:
    image: squid-game-client
    build:
      context: ./client
    ports:
      - "3001:3001"
    depends_on:
      - server
